### PR TITLE
WIP: Fix issues with search back button, use GET for advanced search

### PR DESCRIPTION
**Pull request by pjsier**
Working on #330. This is still a work in progress, but I wanted to get feedback on whether we could use GET for the advanced search instead of POST. From some initial tests, every filter type still seems to work, and exports work as well.

### CODE REVIEW

**Comment by cecilia-donnelly** [comment]
Hey @pjsier -- is this ready for me to look at?  Was there something in particular you wanted me to test?

**Comment by pjsier** [comment]
@cecilia-donnelly right now I just wanted to see if you thought there were any issues with using GET instead of POST for the advanced search. I only just got it working so it's not quite ready to look at yet

**Comment by kfogel** [comment]
I pondered and read up on security implications.  My initial take is that there isn't really much difference, especially over https.  https://stackoverflow.com/questions/198462/is-either-get-or-post-more-secure-than-the-other for more.

**Comment by cecilia-donnelly** [comment]
Hello! Do you think this can be closed? (I happened to be looking in the "mentioned" tab of my PR list on GitHub and saw it hanging around.)

Hope you are both well. :)

**Comment by pjsier** [comment]
That’s fine with me, hope you’re doing well too!

**Pull request closed without merging**
